name: my_timezone
description: A flutter plugin for getting the local timezone of the device on Android, ios, macos.
version: 0.0.2+5
repository: https://github.com/ngmduc2012/my_timezone
funding:
  - https://buymeacoffee.com/ducmng12g
  - https://ko-fi.com/I2I81AEJG8
  - https://github.com/sponsors/ngmduc2012
  - https://paypal.me/ngmduc

environment:
  sdk: ^3.4.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: '>=0.6.3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter:
  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_timezone
        pluginClass: MyTimezonePlugin
      ios:
        pluginClass: MyTimezonePlugin
      macos:
        pluginClass: MyTimezonePlugin
      web:
        pluginClass: MyTimezonePlugin
        fileName: my_timezone_web.dart
screenshots:
  - description: "avatar package"
    path: avatar.png

topics:
  - timezone
  - local-time
  - device-info
  - flutter-plugin
  - cross-platform
